services:
  - type: web
    name: sauna-na-cvetochnoy-backend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: CORS_ORIGIN
        value: https://sauna-na-cvetochnoy.onrender.com 